datasource:
  driver-class-name: ${secret.datasource.driver-class-name}
  username: ${secret.datasource.username}
  password: ${secret.datasource.password}
  url: ${secret.datasource.url}

jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true

security:
  oauth2:
    client:
      registration:
        kakao:
          #          change redirect-uri to prod domain
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao

logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.web: debug
    com.demoboletto: debug

