datasource:
  driver-class-name: ${secret.datasource.driver-class-name}
  username: ${secret.datasource.username}
  password: ${secret.datasource.password}
  url: ${secret.datasource.url}

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: false
      show_sql: false
      use_sql_comments: false

security:
  oauth2:
    client:
      registration:
        kakao:
          #          change redirect-uri to prod domain
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao

logging:
  level:
    root: info
    #    org.springframework.security: debug
    #    org.springframework.web: info
    com.demoboletto: info

