spring:
  datasource:
    driver-class-name: ${datasource.driver-class-name}
    username: ${datasource.username}
    password: ${datasource.password}
    url: ${datasource.url}

  jpa:
    hibernate:
      ddl-auto: ${jpa.hibernate.ddl-auto}
    properties:
      hibernate:
        format_sql: ${jpa.properties.hibernate.format_sql}
        show_sql: ${jpa.properties.hibernate.show_sql}
        use_sql_comments: ${jpa.properties.hibernate.use_sql_comments}
        dialect: ${jpa.properties.hibernate.dialect}
  cloud:
    aws:
      credentials:
        accessKey: ${secret.aws.credentials.accessKey}
        secretKey: ${secret.aws.credentials.secretKey}
      s3:
        bucket: ${secret.aws.s3.bucket}
      region:
        static: ${secret.aws.region.static}

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${secret.oauth.registration.kakao.client-id}
            client-secret: ${secret.oauth.registration.kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: ${security.oauth2.client.registration.kakao.redirect-uri}
            authorization-grant-type: authorization_code
            client-name: kakao
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

apple:
  api_url:
    information: "test"

jwt:
  secret-key: ${secret.jwt.secret-key}
  access-token:
    expire-period: 604800000
  refresh-token:
    expire-period: 604800000

