spring:
  datasource:
    driver-class-name: ${datasource.driver-class-name}
    username: ${datasource.username}
    password: ${datasource.password}
    url: ${datasource.url}

  jpa:
    hibernate:
      ddl-auto: ${jpa.hibernate.ddl-auto}
    properties:
      hibernate:
        format_sql: ${jpa.properties.hibernate.format_sql}
        show_sql: ${jpa.properties.hibernate.show_sql}
        use_sql_comments: ${jpa.properties.hibernate.use_sql_comments}
        dialect: ${jpa.properties.hibernate.dialect}
  cloud:
    oci:
      credentials:
        user: ${secret.oci.credentials.user}
        fingerprint: ${secret.oci.credentials.fingerprint}
        tenancy: ${secret.oci.credentials.tenancy}
        region: ${secret.oci.credentials.region}
        key-file: ${secret.oci.credentials.key_file}
      object-storage:
        bucket: ${secret.oci.object-storage.bucket}
        namespace: ${secret.oci.object-storage.namespace}
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${secret.oauth.registration.kakao.client-id}
            client-secret: ${secret.oauth.registration.kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: ${security.oauth2.client.registration.kakao.redirect-uri}
            authorization-grant-type: authorization_code
            client-name: kakao
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

apple:
  api_url:
    information: https://appleid.apple.com/auth/keys

jwt:
  secret-key: ${secret.jwt.secret-key}
  access-token:
    expire-period: 604800000
  refresh-token:
    expire-period: 604800000

